kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet-subtracter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-subtracter
  template:
    metadata:
      labels:
        app: dotnet-subtracter
    spec:
      containers:
        - name: dotnet-subtracter
          image: dotnet-subtracter
          ports:
            - name: http
              containerPort: 7000
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-subtracter
spec:
  ports:
  - name: "7000"
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: dotnet-subtracter
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-subtracter
spec:
  rules:
    - host: distributd-calculator.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: dotnet-subtracter
                port:
                  number: 7000